language: c
sudo: enabled
dist: xenial
group: stable
os: linux

before_install:
  - sudo ./build.sh prepare
script:
  - sudo ./build.sh build
  - sudo ./build.sh test

#deploy:
#  provider: releases
#  api_key: $GITHUB_OAUTH_TOKEN
#  file: 
#    - rootfs.tgz
#    - Dockerfile
#  skip_cleanup: true
#  on:
#    tags: true
