language: c
sudo: enabled
dist: xenial
group: stable
os: linux

jobs:
  include:
    - stage: prepare
      script: sudo ./build.sh prepare
    - stage: build
      script: sudo ./build.sh build
    - stage: test
      script: sudo ./build.sh test

