language: c
sudo: enabled
dist: xenial
group: stable
os: linux

before_install:
  - sudo ./build.sh install_dep

install:
  - sudo ./build.sh create_arbo
  - sudo ./build.sh get_apk_static
  - sudo ./build.sh get_resin-xbuild 

script:
  - sudo ./build.sh compile_resin-xbuild && \
	sudo ./build.sh install_resin-xbuild && \
	sudo ./build.sh install_rootfs && \
	sudo ./build.sh generate_rootfstgz && \
	sudo ./build.sh test_docker_build && \
	sudo ./build.sh test_docker_use_img

#deploy:
#  provider: releases
#  api_key: $GITHUB_OAUTH_TOKEN
#  file: 
#    - rootfs.tgz
#    - Dockerfile
#  skip_cleanup: true
#  on:
#    tags: true
